# Generated by cucumber-sinatra. (2011-04-23 19:31:34 -0500)

ENV['RACK_ENV'] = 'test'
require File.join(File.dirname(__FILE__), '..', '..', 'lib/app.rb')

require 'capybara'
require 'ruby-debug'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'
require 'database_cleaner/cucumber'
require 'cucumber/rspec/doubles'

Capybara.app = HtmlToCloud

class AppWorld
  include Capybara
  include RSpec::Matchers
  include RSpec::Mocks
end

World do
  AppWorld.new
end

DatabaseCleaner.strategy = :transaction

Before do
  DataMapper.auto_migrate!
end

Debugger.start
