---
   environment: production
   chdir: /var/www/htmltocloud
   address: 127.0.0.1
   user: root
   group: root
   port: 80
   pid: /var/www/htmltocloud/tmp/thin.pid
   log: /var/www/htmltocloud/log/thin.log
   rackup: /var/www/htmltocloud/current/config.ru
   max_conns: 1024
   timeout: 30
   max_persistent_conns: 512
   daemonize: true
